# Desafio 1: Data Cleaning and Preparation

Baixar um dataset do portal do [CEAPS](https://www12.senado.leg.br/transparencia/dados-abertos-transparencia/dados-abertos-ceaps?utm_source=ActiveCampaign&utm_medium=email&utm_content=%237DaysOfCode+-+Ci%C3%AAncia+de+Dados+1%2F7%3A+Data+Cleaning+and+Preparation&utm_campaign=%5BAlura+%237Days+Of+Code%5D%28Java%29+Dia+1%2F7%3A+Consumir+uma+API+de+filmes) (Cota para Exercício da Atividade Parlamentar dos Senadores) e aplicar processos de tratamento e limpeza de dados. Ou seja, identificar inconsistências, como campos que possuem valores nulos ou duplicados, converter campos, corrigir valores monetários, nomes incorretos, formatar campos de CNPJ, etc.

In [1]:
import pandas as pd

In [2]:
dataset2022 = pd.read_csv('/content/despesa_ceaps_2022.csv', sep=';', encoding='ISO-8859-1')
dataset2022

                                                                                                                                                                                                                  ULTIMA ATUALIZACAO  \
ANO  MES SENADOR          TIPO_DESPESA                                       CNPJ_CPF           FORNECEDOR                        DOCUMENTO         DATA       DETALHAMENTO                                        VALOR_REEMBOLSADO
2022 1   ACIR GURGACZ     Aluguel de imóveis para escritório político, co... 004.948.028-63     GILBERTO PISELO DO NASCIMENTO     001/22            03/01/2022 Despesa com pagamento de aluguel de imóvel para...               6000
                          Divulgação da atividade parlamentar                26.320.603/0001-64 INFORMANAHORA                     000000000000310/A 04/01/2022 Despesa com divulgação da atividade parlamentar...               1500
                                                                             13.659.201/0001-47 LINHA PURPURA FOTO E VIDEO LTDA   107               14/01/2022 Despesa com produção de texto e edição de vídeo...               6000
                                                                             23.652.846/0001-01 ROBERTO GUTIERREZ DA ROCHA M.E.I. 187               18/01/2022 Divulgação da atividade parlamentar                              1000
...                                                                                                                                                                                                                              ...
     9   ZEQUINHA MARINHO Passagens aéreas, aquáticas e terrestres nacionais 22.052.777/0001-32 Exceller Tour                     JK9V9A            14/09/2022 Companhia Aérea: AZUL, Localizador: JK9V9A. Pas...            1595,15
                                                                                                                                  VKKHPO            16/09/2022 Companhia Aérea: GOL, Localizador: VKKHPO. Pass...            2843,24
     10  ZEQUINHA MARINHO Passagens aéreas, aquáticas e terrestres nacionais 22.052.777/0001-32 Exceller Tour                     DNLRGP            03/10/2022 Companhia Aérea: GOL, Localizador: DNLRGP. Pass...            3275,31
                                                                                                                                  IYNZYM            04/10/2022 Companhia Aérea: TAM, Localizador: IYNZYM. Pass...            2024,44
                                                                                                                                  ZWVRYH            06/10/2022 Companhia Aérea: AZUL, Localizador: ZWVRYH. Pas...            1767,66

                                                                                                                                                                                                                  18/10/2022 02:02
ANO  MES SENADOR          TIPO_DESPESA                                       CNPJ_CPF           FORNECEDOR                        DOCUMENTO         DATA       DETALHAMENTO                                          COD_DOCUMENTO
2022 1   ACIR GURGACZ     Aluguel de imóveis para escritório político, co... 004.948.028-63     GILBERTO PISELO DO NASCIMENTO     001/22            03/01/2022 Despesa com pagamento de aluguel de imóvel para...          2173614
                          Divulgação da atividade parlamentar                26.320.603/0001-64 INFORMANAHORA                     000000000000310/A 04/01/2022 Despesa com divulgação da atividade parlamentar...          2173615
                                                                             13.659.201/0001-47 LINHA PURPURA FOTO E VIDEO LTDA   107               14/01/2022 Despesa com produção de texto e edição de vídeo...          2173616
                                                                             23.652.846/0001-01 ROBERTO GUTIERREZ DA ROCHA M.E.I. 187               18/01/2022 Divulgação da atividade parlamentar                         2173618
...                                                                                                                                                                                                                            ...
     9   ZEQUINHA MARINHO Passagens aéreas, aquáticas e terrestres nacionais 22.052.777/0001-32 Exceller Tour                     JK9V9A            14/09/2022 Companhia Aérea: AZUL, Localizador: JK9V9A. Pas...          2187566
                                                                                                                                  VKKHPO            16/09/2022 Companhia Aérea: GOL, Localizador: VKKHPO. Pass...          2187565
     10  ZEQUINHA MARINHO Passagens aéreas, aquáticas e terrestres nacionais 22.052.777/0001-32 Exceller Tour                     DNLRGP            03/10/2022 Companhia Aérea: GOL, Localizador: DNLRGP. Pass...          2187707
                                                                                                                                  IYNZYM            04/10/2022 Companhia Aérea: TAM, Localizador: IYNZYM. Pass...          2188009
                                                                                                                                  ZWVRYH            06/10/2022 Companhia Aérea: AZUL, Localizador: ZWVRYH. Pas...          2188011

[12579 rows x 2 columns]

No arquivo original, a primeira linha informava a última atialização realizada. Isso fez com que o arquivo fosse interpretado com 12579 linhas e 2 colunas. Para ignorar a primeira linha do arquivo, utilizei o parâmetro ‘skiprow’.

In [3]:
dataset2022 = pd.read_csv('/content/despesa_ceaps_2022.csv', sep=';', encoding='ISO-8859-1', skiprows=1)
dataset2022

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2022,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/22,03/01/2022,Despesa com pagamento de aluguel de imóvel par...,6000,2173614
1,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,26.320.603/0001-64,INFORMANAHORA,000000000000310/A,04/01/2022,Despesa com divulgação da atividade parlamenta...,1500,2173615
2,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,13.659.201/0001-47,LINHA PURPURA FOTO E VIDEO LTDA,107,14/01/2022,Despesa com produção de texto e edição de víde...,6000,2173616
3,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,23.652.846/0001-01,ROBERTO GUTIERREZ DA ROCHA M.E.I.,187,18/01/2022,Divulgação da atividade parlamentar,1000,2173618
4,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,08.941.827/0001-01,RONDONIA DINÂMICA COM. E SERV. DE INFORMÁTICA ...,000000000001772/A,17/01/2022,Divulgação da atividade parlamentar,2000,2173617
...,...,...,...,...,...,...,...,...,...,...,...
12573,2022,9,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,JK9V9A,14/09/2022,"Companhia Aérea: AZUL, Localizador: JK9V9A. Pa...","1595,15",2187566
12574,2022,9,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,VKKHPO,16/09/2022,"Companhia Aérea: GOL, Localizador: VKKHPO. Pas...","2843,24",2187565
12575,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,DNLRGP,03/10/2022,"Companhia Aérea: GOL, Localizador: DNLRGP. Pas...","3275,31",2187707
12576,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,IYNZYM,04/10/2022,"Companhia Aérea: TAM, Localizador: IYNZYM. Pas...","2024,44",2188009
12577,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,ZWVRYH,06/10/2022,"Companhia Aérea: AZUL, Localizador: ZWVRYH. Pa...","1767,66",2188011

In [4]:
dataset2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12578 entries, 0 to 12577
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                12578 non-null  int64
 1   MES                12578 non-null  int64
 2   SENADOR            12578 non-null  object
 3   TIPO_DESPESA       12578 non-null  object
 4   CNPJ_CPF           12578 non-null  object
 5   FORNECEDOR         12578 non-null  object
 6   DOCUMENTO          11852 non-null  object
 7   DATA               12578 non-null  object
 8   DETALHAMENTO       6747 non-null   object
 9   VALOR_REEMBOLSADO  12578 non-null  object
 10  COD_DOCUMENTO      12578 non-null  int64
dtypes: int64(3), object(8)
memory usage: 1.1+ MB

Ao solicitar as informações do dataset, somente a coluna ‘DETALHAMENTO’ possui valores nulos. Dependendo do ‘TIPO_DESPESA’, esta falta de informação pode dificultar a análise do gasto.
Porém, os nulos podem ser preenchidos como ‘Não especificado’, ou algo similar, para não deixar lacunas no dataset.

In [5]:
dataset2022['DETALHAMENTO'].fillna('Não informado', inplace=True)

Também há dados nulos na variável documento, que também serão substituídos por ‘Não informado’:

In [6]:
dataset2022['DOCUMENTO'].fillna('Não informado', inplace=True)

In [7]:
dataset2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12578 entries, 0 to 12577
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                12578 non-null  int64
 1   MES                12578 non-null  int64
 2   SENADOR            12578 non-null  object
 3   TIPO_DESPESA       12578 non-null  object
 4   CNPJ_CPF           12578 non-null  object
 5   FORNECEDOR         12578 non-null  object
 6   DOCUMENTO          12578 non-null  object
 7   DATA               12578 non-null  object
 8   DETALHAMENTO       12578 non-null  object
 9   VALOR_REEMBOLSADO  12578 non-null  object
 10  COD_DOCUMENTO      12578 non-null  int64
dtypes: int64(3), object(8)
memory usage: 1.1+ MB

Depois, a mudança de tipo de variável será para ‘DATA’:

In [8]:
pd.to_datetime(dataset2022['DATA'].str.title(), format='%d/%m/%Y')

0       2022-01-03
1       2022-01-04
2       2022-01-14
3       2022-01-18
4       2022-01-17
           ...
12573   2022-09-14
12574   2022-09-16
12575   2022-10-03
12576   2022-10-04
12577   2022-10-06
Name: DATA, Length: 12578, dtype: datetime64[ns]

In [9]:
dataset2022['DATA'] = pd.to_datetime(dataset2022['DATA'].str.title(), format='%d/%m/%Y')
dataset2022

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2022,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/22,2022-01-03,Despesa com pagamento de aluguel de imóvel par...,6000,2173614
1,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,26.320.603/0001-64,INFORMANAHORA,000000000000310/A,2022-01-04,Despesa com divulgação da atividade parlamenta...,1500,2173615
2,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,13.659.201/0001-47,LINHA PURPURA FOTO E VIDEO LTDA,107,2022-01-14,Despesa com produção de texto e edição de víde...,6000,2173616
3,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,23.652.846/0001-01,ROBERTO GUTIERREZ DA ROCHA M.E.I.,187,2022-01-18,Divulgação da atividade parlamentar,1000,2173618
4,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,08.941.827/0001-01,RONDONIA DINÂMICA COM. E SERV. DE INFORMÁTICA ...,000000000001772/A,2022-01-17,Divulgação da atividade parlamentar,2000,2173617
...,...,...,...,...,...,...,...,...,...,...,...
12573,2022,9,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,JK9V9A,2022-09-14,"Companhia Aérea: AZUL, Localizador: JK9V9A. Pa...","1595,15",2187566
12574,2022,9,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,VKKHPO,2022-09-16,"Companhia Aérea: GOL, Localizador: VKKHPO. Pas...","2843,24",2187565
12575,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,DNLRGP,2022-10-03,"Companhia Aérea: GOL, Localizador: DNLRGP. Pas...","3275,31",2187707
12576,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,IYNZYM,2022-10-04,"Companhia Aérea: TAM, Localizador: IYNZYM. Pas...","2024,44",2188009
12577,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,ZWVRYH,2022-10-06,"Companhia Aérea: AZUL, Localizador: ZWVRYH. Pa...","1767,66",2188011

Por último, retirar a vírgula nos valores reembolsados e transformar em float:

In [10]:
dataset2022['VALOR_REEMBOLSADO'].str.replace(',','.').astype(float)

0        6000.00
1        1500.00
2        6000.00
3        1000.00
4        2000.00
          ...
12573    1595.15
12574    2843.24
12575    3275.31
12576    2024.44
12577    1767.66
Name: VALOR_REEMBOLSADO, Length: 12578, dtype: float64

In [11]:
dataset2022['VALOR_REEMBOLSADO'] = dataset2022['VALOR_REEMBOLSADO'].str.replace(',','.').astype(float)
dataset2022

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2022,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/22,2022-01-03,Despesa com pagamento de aluguel de imóvel par...,6000.00,2173614
1,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,26.320.603/0001-64,INFORMANAHORA,000000000000310/A,2022-01-04,Despesa com divulgação da atividade parlamenta...,1500.00,2173615
2,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,13.659.201/0001-47,LINHA PURPURA FOTO E VIDEO LTDA,107,2022-01-14,Despesa com produção de texto e edição de víde...,6000.00,2173616
3,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,23.652.846/0001-01,ROBERTO GUTIERREZ DA ROCHA M.E.I.,187,2022-01-18,Divulgação da atividade parlamentar,1000.00,2173618
4,2022,1,ACIR GURGACZ,Divulgação da atividade parlamentar,08.941.827/0001-01,RONDONIA DINÂMICA COM. E SERV. DE INFORMÁTICA ...,000000000001772/A,2022-01-17,Divulgação da atividade parlamentar,2000.00,2173617
...,...,...,...,...,...,...,...,...,...,...,...
12573,2022,9,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,JK9V9A,2022-09-14,"Companhia Aérea: AZUL, Localizador: JK9V9A. Pa...",1595.15,2187566
12574,2022,9,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,VKKHPO,2022-09-16,"Companhia Aérea: GOL, Localizador: VKKHPO. Pas...",2843.24,2187565
12575,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,DNLRGP,2022-10-03,"Companhia Aérea: GOL, Localizador: DNLRGP. Pas...",3275.31,2187707
12576,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,IYNZYM,2022-10-04,"Companhia Aérea: TAM, Localizador: IYNZYM. Pas...",2024.44,2188009
12577,2022,10,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,ZWVRYH,2022-10-06,"Companhia Aérea: AZUL, Localizador: ZWVRYH. Pa...",1767.66,2188011

Para finalizar o tratamento, verifiquei se há informações duplicadas:

In [12]:
duplicados = dataset2022.duplicated()
duplicados.sum()

0

Com as variáveis tratadas, chegou a hora de adicionar os dados de anos anteriores (2018, 2019, 2020 e 2021):

In [13]:
dados2018 = ('/content/despesa_ceaps_2018.csv')
dataset2018 = pd.read_csv(dados2018, sep=';', encoding='ISO-8859-1', skiprows=1)
dados2019 = ('/content/despesa_ceaps_2019.csv')
dataset2019 = pd.read_csv(dados2019, sep=';', encoding='ISO-8859-1', skiprows=1)
dados2020 = ('/content/despesa_ceaps_2020.csv')
dataset2020 = pd.read_csv(dados2020, sep=';', encoding='ISO-8859-1', skiprows=1)
dados2021 = ('/content/despesa_ceaps_2021.csv')
dataset2021 = pd.read_csv(dados2021, sep=';', encoding='ISO-8859-1', skiprows=1)

In [14]:
from datetime import datetime, timezone
def ler_arquivo(nome_dataset): 
  nome_dataset['DETALHAMENTO'].fillna('Não informado', inplace=True)
  nome_dataset['DOCUMENTO'].fillna('Não informado', inplace=True)
  nome_dataset['VALOR_REEMBOLSADO'] = nome_dataset['VALOR_REEMBOLSADO'].str.replace(',','.').astype(float)
  nome_dataset['DATA'] = pd.to_datetime(nome_dataset['DATA'].str.title(), format='%d/%m/%Y', errors='coerce')
  nome_dataset['DATA'].replace(inplace = True)

In [15]:
ler_arquivo(dataset2018)

In [16]:
dataset2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24492 entries, 0 to 24491
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                24492 non-null  int64
 1   MES                24492 non-null  int64
 2   SENADOR            24492 non-null  object
 3   TIPO_DESPESA       24492 non-null  object
 4   CNPJ_CPF           24492 non-null  object
 5   FORNECEDOR         24492 non-null  object
 6   DOCUMENTO          24492 non-null  object
 7   DATA               24492 non-null  datetime64[ns]
 8   DETALHAMENTO       24492 non-null  object
 9   VALOR_REEMBOLSADO  24492 non-null  float64
 10  COD_DOCUMENTO      24492 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 2.1+ MB

In [18]:
ler_arquivo(dataset2019)

In [19]:
dataset2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21634 entries, 0 to 21633
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                21634 non-null  int64
 1   MES                21634 non-null  int64
 2   SENADOR            21634 non-null  object
 3   TIPO_DESPESA       21634 non-null  object
 4   CNPJ_CPF           21634 non-null  object
 5   FORNECEDOR         21634 non-null  object
 6   DOCUMENTO          21634 non-null  object
 7   DATA               21634 non-null  datetime64[ns]
 8   DETALHAMENTO       21634 non-null  object
 9   VALOR_REEMBOLSADO  21634 non-null  float64
 10  COD_DOCUMENTO      21634 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 1.8+ MB

In [20]:
ler_arquivo(dataset2020)

In [21]:
dataset2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14090 entries, 0 to 14089
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                14090 non-null  int64
 1   MES                14090 non-null  int64
 2   SENADOR            14090 non-null  object
 3   TIPO_DESPESA       14090 non-null  object
 4   CNPJ_CPF           14090 non-null  object
 5   FORNECEDOR         14090 non-null  object
 6   DOCUMENTO          14090 non-null  object
 7   DATA               14090 non-null  datetime64[ns]
 8   DETALHAMENTO       14090 non-null  object
 9   VALOR_REEMBOLSADO  14090 non-null  float64
 10  COD_DOCUMENTO      14090 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 1.2+ MB

In [22]:
ler_arquivo(dataset2021)

In [23]:
dataset2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16827 entries, 0 to 16826
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                16827 non-null  int64
 1   MES                16827 non-null  int64
 2   SENADOR            16827 non-null  object
 3   TIPO_DESPESA       16827 non-null  object
 4   CNPJ_CPF           16827 non-null  object
 5   FORNECEDOR         16827 non-null  object
 6   DOCUMENTO          16827 non-null  object
 7   DATA               16827 non-null  datetime64[ns]
 8   DETALHAMENTO       16827 non-null  object
 9   VALOR_REEMBOLSADO  16827 non-null  float64
 10  COD_DOCUMENTO      16827 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 1.4+ MB



---



---

Criando o dataset unificado:

In [32]:
ceaps_2018_2022 = pd.concat([dataset2018, dataset2019, dataset2020, dataset2021, dataset2022], ignore_index=True)

In [33]:
ceaps_2018_2022.sample(10)

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
37104,2019,2,MARA GABRILLI,"Locomoção, hospedagem, alimentação, combustíve...",00.306.597/0076-14,CASCOL COMBUSTÍVEL PARA VEICULOS LTDA,324752,2019-02-12,Aquisição de combustível para veículos utiliza...,200.00,2115235
8171,2018,9,GLEISI HOFFMANN,"Aluguel de imóveis para escritório político, c...",04.549.702/0001-80,CARPATI Administração de Bens Ltda,s/n,2018-08-30,Despesa de aluguel do imóvel destinado ao escr...,3839.40,2105352
86202,2022,8,NILDA GONDIM,"Locomoção, hospedagem, alimentação, combustíve...",01.631.699/0001-50,POSTO DE COMBUSTIVEIS MARILIA LTDA,95255,2022-08-19,Não informado,250.76,2185711
84665,2022,3,LUIS CARLOS HEINZE,"Locomoção, hospedagem, alimentação, combustíve...",93.489.243/0006-20,COML. BUFFON COMB. E TRANSP. LTDA - POSTO 06,834090,2022-03-04,Não informado,340.08,2175505
89221,2022,5,ZENAIDE MAIA,"Locomoção, hospedagem, alimentação, combustíve...",08.399.834/0001-23,POSTO PLANALTO LTDA,375117,2022-05-27,Não informado,449.35,2180980
54094,2020,7,MAJOR OLIMPIO,"Aluguel de imóveis para escritório político, c...",02.558.157/0001-62,Telefônica Brasil S/A,0031246139,2020-07-23,Não informado,642.92,2146969
24823,2019,8,ALESSANDRO VIEIRA,"Locomoção, hospedagem, alimentação, combustíve...",21.685.600/0002-91,Peixe na Rede,12519,2019-08-08,Alimentação do parlamentar.,33.65,2128618
87979,2022,2,SÉRGIO PETECÃO,"Contratação de consultorias, assessorias, pesq...",12.980.692/0001-60,P. H. A. RAMALHO - ME,66,2022-02-28,Não informado,77012.00,2175346
11846,2018,10,JOSÉ PIMENTEL,"Aluguel de imóveis para escritório político, c...",40.432.544/0161-40,CLARO S/A.,1694344,2018-11-01,DESPESA COM INTERNET NO ESCRITÓRIO PARLAMENTAR...,240.90,2110162
19713,2018,8,ROBERTO ROCHA,"Contratação de consultorias, assessorias, pesq...",12.757.808/0001-05,R.C. PEREIRA JUNIOR SERVIÇOS EIRELI,368,2018-08-05,Serviços prestados de manutenção da central te...,300.00,2105016

Exportando o dataset:

In [35]:
ceaps_2018_2022.to_csv('ceaps_2018_2022.csv', sep = ',', index = False)